trigger:
- main

variables:
  node_version: '20.x'
  source_dir: '$(System.DefaultWorkingDirectory)'
  build_dir: '$(System.DefaultWorkingDirectory)/build'

stages:

# ---------------- BUILD STAGE ----------------
- stage: Build
  displayName: Build React App
  jobs:
  - job: BuildJob
    pool:
      name: Default

    steps:
    - checkout: self

    # Install Node
    - task: NodeTool@0
      inputs:
        versionSpec: $(node_version)
      displayName: Install Node.js

    # Install dependencies
    - script: npm install
      workingDirectory: $(source_dir)
      displayName: Install npm packages

    # Build React app
    - script: npm run build
      workingDirectory: $(source_dir)
      displayName: Build React app

    # Archive build folder
    - task: ArchiveFiles@2
      displayName: Zip build folder
      inputs:
        rootFolderOrFile: $(build_dir)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/react-build.zip
        replaceExistingArchive: true

    # Publish artifact
    - task: PublishPipelineArtifact@1
      displayName: Publish artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/react-build.zip
        artifact: react-build

# ---------------- DEPLOY STAGE ----------------
- stage: Deploy
  displayName: Deploy React App
  dependsOn: Build

  jobs:
  - deployment: DeployJob
    environment: production
    pool:
      name: Default

    strategy:
      runOnce:
        deploy:
          steps:

          # Download artifact
          - download: current
            artifact: react-build

          # Deploy to Azure Web App
          - task: AzureWebApp@1
            displayName: Deploy to Azure Web App
            inputs:
              azureSubscription: CICD-service-connection
              appType: webAppLinux
              appName: cicdcd
              package: $(Pipeline.Workspace)/react-build/react-build.zip